twig:
    # cimo :
    paths:
        '%kernel.project_dir%/templates': templateRoot
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # cimo +
    globals:
        pathRoot: '%kernel.project_dir%'
        pathSrc: '%kernel.project_dir%/src'
        pathPublic: '%kernel.project_dir%/public'
    exception_controller: null